### ISSUE TITLE
[BUG]: your FCU don't support AUTOPILOT_VERSION

### ISSUE THREAD

**Issue by MichaelLeibbrand** [Robotic-Decision-Making-Lab/blue#222] opened 2024-08-02 10:09 UTC
### Issue Description

Gazebo Simulation does not work anymore.

### Steps to Reproduce

- pull and run humble-desktop-nvidia image
- launch BlueROV2 in simulation: ros2 launch blue_demos bluerov2_demo.launch.yaml use_sim:=true

### Expected Behavior

Gazebo should run and display bluerov2 in world

### Error Message

```bash
[mavros_node-2] [WARN] [1722592485.697594400] [mavros.sys]: VER: broadcast request timeout, retries left 4
[mavros_node-2] [WARN] [1722592486.700242662] [mavros.sys]: VER: broadcast request timeout, retries left 3
[mavros_node-2] [WARN] [1722592487.700968003] [mavros.sys]: VER: unicast request timeout, retries left 2
[create-6] [INFO] [1722592488.485097969] [ros_gz_sim]: Requesting list of world names.
[mavros_node-2] [WARN] [1722592488.694910497] [mavros.sys]: VER: unicast request timeout, retries left 1
[mavros_node-2] [WARN] [1722592489.694949862] [mavros.sys]: VER: unicast request timeout, retries left 0
[mavros_node-2] [WARN] [1722592490.694989443] [mavros.sys]: VER: your FCU don't support AUTOPILOT_VERSION, switched to default capabilities
[create-6] [INFO] [1722592493.485265919] [ros_gz_sim]: Requesting list of world names.
[ruby $(which gz) sim-8] [Wrn] [Gui.cc:269] Waited for 10s for a subscriber to [/gazebo/starting_world] and got none.
```

### Runtime Environment

Ubuntu 22.04

### Additional Context

Simulation and Teleoperation was working fine before

**Comment by evan-palmer** [comment] 2024-08-02 20:32
Thanks for reporting this @MichaelLeibbrand! I'll take a look. I must have broken something on a recent backport.

**Comment by evan-palmer** [comment] 2024-08-08 19:26
Which image are you using to test this @MichaelLeibbrand? I've just done some tests with the `*-nvidia-desktop` image and things seem to be working there. Though I also just tested the version which uses `nouveau` drivers and things seem to fail there due to a change in the X11 forwarding (that I need to add an issue for)

**Comment by MichaelLeibbrand** [comment] 2024-08-14 08:28
I use the humble-desktop-nvidia image:
https://raw.githubusercontent.com/Robotic-Decision-Making-Lab/blue/humble/.docker/compose/nvidia-desktop.yaml

unfortunately I still encounter the same issues.

**Comment by evan-palmer** [comment] 2024-08-15 03:11
Would you be willing to upload the full log?

**Comment by evan-palmer** [comment] 2024-09-19 19:10
After meeting with @MichaelLeibbrand, we determined that the issue was being caused by local networking configurations documented in [gz-sim!2285](https://github.com/gazebosim/gz-sim/issues/1879). I think it would be worth updating the documentation to describe this in a troubleshooting step. The error message doesn't indicate that the issue could be caused by networking configurations, so it appears a bit cryptic.

**Comment by evan-palmer** [comment] 2024-09-19 19:17
```
[INFO] [launch]: All log files can be found below /home/blue/.ros/log/2024-09-19-16-09-55-753945-michael-leibbrand-1119 
[INFO] [launch]: Default logging verbosity is set to INFO 
[INFO] [robot_state_publisher-1]: process started with pid [1131] 
[INFO] [mavros_node-2]: process started with pid [1133] 
[INFO] [parameter_bridge-3]: process started with pid [1135] 
[INFO] [parameter_bridge-4]: process started with pid [1137] 
[INFO] [parameter_bridge-5]: process started with pid [1139] 
[INFO] [create-6]: process started with pid [1141] 
[INFO] [ardusub-7]: process started with pid [1143] 
[INFO] [ruby $(which gz) sim-8]: process started with pid [1145] 
[INFO] [ardusub_manager-9]: process started with pid [1147] 
[INFO] [gazebo_localizer-10]: process started with pid [1149] 
[INFO] [static_transform_publisher-11]: process started with pid [1152] 
[INFO] [static_transform_publisher-12]: process started with pid [1154] 
[INFO] [static_transform_publisher-13]: process started with pid [1156] 
[INFO] [static_transform_publisher-14]: process started with pid [1158] 
[INFO] [static_transform_publisher-15]: process started with pid [1161] 
[INFO] [static_transform_publisher-16]: process started with pid [1163] 
[INFO] [static_transform_publisher-17]: process started with pid [1165] 
[INFO] [static_transform_publisher-18]: process started with pid [1169] 
[INFO] [static_transform_publisher-19]: process started with pid [1185] 
[ardusub-7] bind port 5760 for SERIAL0 
[ardusub-7] SERIAL0 on TCP port 5760 
[mavros_node-2] [INFO] [1726762196.663557695] [mavros_node]: Starting mavros_node container 
[mavros_node-2] [INFO] [1726762196.663676655] [mavros_node]: FCU URL: tcp://localhost 
[mavros_node-2] [INFO] [1726762196.663687050] [mavros_node]: GCS URL: udp://@localhost:14550 
[mavros_node-2] [INFO] [1726762196.663692426] [mavros_node]: UAS Prefix: /uas1 
[mavros_node-2] [INFO] [1726762196.663697912] [mavros_node]: Starting mavros router node 
[static_transform_publisher-18] [INFO] [1726762196.665709370] [map_to_map_ned]: Spinning until stopped - publishing transform 
[static_transform_publisher-18] translation: ('0.000000', '0.000000', '0.000000') 
[static_transform_publisher-18] rotation: ('1.000000', '0.000000', '-0.000000', '-0.000204') 
[static_transform_publisher-18] from 'map' to 'map_ned' 
[static_transform_publisher-11] [INFO] [1726762196.678081273] [base_link_to_thruster1]: Spinning until stopped - publishing transform 
[static_transform_publisher-11] translation: ('0.140000', '-0.092000', '0.000000') 
[static_transform_publisher-11] rotation: ('-0.270728', '0.653228', '0.270861', '0.653172') 
[static_transform_publisher-11] from 'base_link' to 'thruster1' 
[static_transform_publisher-12] [INFO] [1726762196.690074040] [base_link_to_thruster2]: Spinning until stopped - publishing transform 
[static_transform_publisher-12] translation: ('0.140000', '0.092000', '0.000000') 
[static_transform_publisher-12] rotation: ('0.270535', '0.653308', '-0.270401', '0.653363') 
[static_transform_publisher-12] from 'base_link' to 'thruster2' 
[static_transform_publisher-19] [INFO] [1726762196.691427412] [odom_to_odom_ned]: Spinning until stopped - publishing transform 
[static_transform_publisher-19] translation: ('0.000000', '0.000000', '0.000000') 
[static_transform_publisher-19] rotation: ('1.000000', '0.000000', '-0.000000', '-0.000204') 
[static_transform_publisher-19] from 'odom' to 'odom_ned' 
[static_transform_publisher-13] [INFO] [1726762196.693079982] [base_link_to_thruster3]: Spinning until stopped - publishing transform 
[static_transform_publisher-13] translation: ('-0.150000', '-0.092000', '0.000000') 
[static_transform_publisher-13] rotation: ('-0.653228', '0.270728', '0.653283', '0.270595') 
[static_transform_publisher-13] from 'base_link' to 'thruster3' 
[parameter_bridge-5] [INFO] [1726762196.696974780] [ros_gz_bridge]: Creating GZ->ROS Bridge: [/model/bluerov2/odometry (gz.msgs.Odometry) -> /model/bluerov2/odometry (nav_msgs/msg/Odometry)] (Lazy 0) 
[static_transform_publisher-14] [INFO] [1726762196.698711120] [base_link_to_thruster4]: Spinning until stopped - publishing transform 
[static_transform_publisher-14] translation: ('-0.150000', '0.092000', '0.000000') 
[static_transform_publisher-14] rotation: ('-0.653308', '-0.270535', '0.653253', '-0.270668') 
[static_transform_publisher-14] from 'base_link' to 'thruster4' 
[static_transform_publisher-17] [INFO] [1726762196.703251929] [base_link_to_base_link_fsd]: Spinning until stopped - publishing transform 
[static_transform_publisher-17] translation: ('0.000000', '0.000000', '0.000000') 
[static_transform_publisher-17] rotation: ('1.000000', '0.000000', '-0.000000', '-0.000204') 
[static_transform_publisher-17] from 'base_link' to 'base_link_fsd' 
[static_transform_publisher-16] [INFO] [1726762196.708834817] [base_link_to_thruster6]: Spinning until stopped - publishing transform 
[static_transform_publisher-16] translation: ('0.000000', '0.109000', '0.077000') 
[static_transform_publisher-16] rotation: ('0.000000', '0.000000', '0.000000', '1.000000') 
[static_transform_publisher-16] from 'base_link' to 'thruster6' 
[static_transform_publisher-15] [INFO] [1726762196.715014456] [base_link_to_thruster5]: Spinning until stopped - publishing transform 
[static_transform_publisher-15] translation: ('0.000000', '-0.109000', '0.077000') 
[static_transform_publisher-15] rotation: ('0.000000', '0.000000', '0.000000', '1.000000') 
[static_transform_publisher-15] from 'base_link' to 'thruster5' 
[parameter_bridge-4] [INFO] [1726762196.718135682] [ros_gz_bridge]: Creating GZ->ROS Bridge: [/camera/image_raw (gz.msgs.Image) -> /camera/image_raw (sensor_msgs/msg/Image)] (Lazy 0) 
[mavros_node-2] [INFO] [1726762196.724921401] [mavros_router]: Built-in SIMD instructions: SSE, SSE2 
[mavros_node-2] [INFO] [1726762196.724975996] [mavros_router]: Built-in MAVLink package version: 2024.6.6 
[mavros_node-2] [INFO] [1726762196.724988187] [mavros_router]: Known MAVLink dialects: common ardupilotmega ASLUAV AVSSUAS all csAirLink cubepilot development icarous matrixpilot paparazzi standard storm32 uAvionix ualberta 
[mavros_node-2] [INFO] [1726762196.724993759] [mavros_router]: MAVROS Router started 
[mavros_node-2] [INFO] [1726762196.725034076] [mavros_router]: Requested to add endpoint: type: 0, url: tcp://localhost 
[mavros_node-2] [INFO] [1726762196.725057712] [mavros_router]: Endpoint link[1000] created 
[mavros_node-2] [INFO] [1726762196.725645396] [mavros_router]: link[1000] opened successfully 
[mavros_node-2] [INFO] [1726762196.725738679] [mavros_router]: Requested to add endpoint: type: 1, url: udp://@localhost:14550 
[mavros_node-2] [INFO] [1726762196.725758077] [mavros_router]: Endpoint link[1001] created 
[mavros_node-2] [INFO] [1726762196.726813547] [mavros_router]: link[1001] opened successfully 
[mavros_node-2] [INFO] [1726762196.727582391] [mavros_router]: Requested to add endpoint: type: 2, url: /uas1 
[mavros_node-2] [INFO] [1726762196.727613657] [mavros_router]: Endpoint link[1002] created 
[create-6] [INFO] [1726762196.728021570] [ros_gz_sim]: Requesting list of world names. 
[parameter_bridge-3] [INFO] [1726762196.730658051] [ros_gz_bridge]: Creating GZ->ROS Bridge: [/clock (gz.msgs.Clock) -> /clock (rosgraph_msgs/msg/Clock)] (Lazy 0) 
[mavros_node-2] [INFO] [1726762196.730704952] [mavros_router]: link[1002] opened successfully 
[mavros_node-2] [INFO] [1726762196.730983651] [mavros_node]: Starting mavros uas node 
[robot_state_publisher-1] [INFO] [1726762196.742636860] [robot_state_publisher]: got segment base_footprint 
[robot_state_publisher-1] [INFO] [1726762196.742770157] [robot_state_publisher]: got segment base_link 
[robot_state_publisher-1] [INFO] [1726762196.742783594] [robot_state_publisher]: got segment camera_link 
[robot_state_publisher-1] [INFO] [1726762196.742789596] [robot_state_publisher]: got segment camera_mount_link 
[robot_state_publisher-1] [INFO] [1726762196.742795127] [robot_state_publisher]: got segment thruster1 
[robot_state_publisher-1] [INFO] [1726762196.742799790] [robot_state_publisher]: got segment thruster2 
[robot_state_publisher-1] [INFO] [1726762196.742804418] [robot_state_publisher]: got segment thruster3 
[robot_state_publisher-1] [INFO] [1726762196.742809349] [robot_state_publisher]: got segment thruster4 
[robot_state_publisher-1] [INFO] [1726762196.742814771] [robot_state_publisher]: got segment thruster5 
[robot_state_publisher-1] [INFO] [1726762196.742820115] [robot_state_publisher]: got segment thruster6 
[mavros_node-2] [INFO] [1726762196.792934085] [mavros]: UAS Executor started, threads: 16 
[mavros_node-2] [INFO] [1726762196.793031306] [mavros]: Plugin actuator_control ignored 
[mavros_node-2] [INFO] [1726762196.793072376] [mavros]: Plugin adsb ignored 
[mavros_node-2] [INFO] [1726762196.793082447] [mavros]: Plugin altitude ignored 
[mavros_node-2] [INFO] [1726762196.793088450] [mavros]: Plugin cam_imu_sync ignored 
[mavros_node-2] [INFO] [1726762196.793095089] [mavros]: Plugin camera ignored 
[mavros_node-2] [INFO] [1726762196.793101147] [mavros]: Plugin cellular_status ignored 
[mavros_node-2] [INFO] [1726762196.819153619] [mavros]: Plugin command created 
[mavros_node-2] [INFO] [1726762196.819213340] [mavros]: Plugin command initialized 
[mavros_node-2] [INFO] [1726762196.819225643] [mavros]: Plugin companion_process_status ignored 
[mavros_node-2] [INFO] [1726762196.819231040] [mavros]: Plugin debug_value ignored 
[mavros_node-2] [INFO] [1726762196.819235082] [mavros]: Plugin distance_sensor ignored 
[mavros_node-2] [INFO] [1726762196.819239496] [mavros]: Plugin esc_status ignored 
[mavros_node-2] [INFO] [1726762196.819243221] [mavros]: Plugin esc_telemetry ignored 
[mavros_node-2] [INFO] [1726762196.819246608] [mavros]: Plugin fake_gps ignored 
[mavros_node-2] [INFO] [1726762196.819250417] [mavros]: Plugin ftp ignored 
[mavros_node-2] [INFO] [1726762196.819254739] [mavros]: Plugin geofence ignored 
[mavros_node-2] [INFO] [1726762196.819258235] [mavros]: Plugin gimbal_control ignored 
[mavros_node-2] [INFO] [1726762196.832007295] [mavros]: Plugin global_position created 
[mavros_node-2] [INFO] [1726762196.832126925] [mavros]: Plugin global_position initialized 
[mavros_node-2] [INFO] [1726762196.832141748] [mavros]: Plugin gps_input ignored 
[mavros_node-2] [INFO] [1726762196.832149240] [mavros]: Plugin gps_rtk ignored 
[mavros_node-2] [INFO] [1726762196.832156039] [mavros]: Plugin gps_status ignored 
[mavros_node-2] [INFO] [1726762196.832162952] [mavros]: Plugin guided_target ignored 
[mavros_node-2] [INFO] [1726762196.832170148] [mavros]: Plugin hil ignored 
[mavros_node-2] [INFO] [1726762196.832176451] [mavros]: Plugin home_position ignored 
[mavros_node-2] [INFO] [1726762196.842177118] [mavros]: Plugin imu created 
[mavros_node-2] [INFO] [1726762196.842235068] [mavros]: Plugin imu initialized 
[mavros_node-2] [INFO] [1726762196.842243248] [mavros]: Plugin landing_target ignored 
[mavros_node-2] [INFO] [1726762196.854446653] [mavros]: Plugin local_position created 
[mavros_node-2] [INFO] [1726762196.854521677] [mavros]: Plugin local_position initialized 
[mavros_node-2] [INFO] [1726762196.854532543] [mavros]: Plugin log_transfer ignored 
[mavros_node-2] [INFO] [1726762196.854537898] [mavros]: Plugin mag_calibration_status ignored 
[mavros_node-2] [INFO] [1726762196.854542406] [mavros]: Plugin manual_control ignored 
[mavros_node-2] [INFO] [1726762196.854546240] [mavros]: Plugin mocap_pose_estimate ignored 
[mavros_node-2] [INFO] [1726762196.854550089] [mavros]: Plugin mount_control ignored 
[mavros_node-2] [INFO] [1726762196.854554314] [mavros]: Plugin nav_controller_output ignored 
[mavros_node-2] [INFO] [1726762196.854666211] [mavros]: Plugin obstacle_distance ignored 
[mavros_node-2] [INFO] [1726762196.854672890] [mavros]: Plugin odometry ignored 
[mavros_node-2] [INFO] [1726762196.854678204] [mavros]: Plugin onboard_computer_status ignored 
[mavros_node-2] [INFO] [1726762196.854682614] [mavros]: Plugin optical_flow ignored 
[mavros_node-2] [INFO] [1726762196.863815340] [mavros]: Plugin param created 
[mavros_node-2] [INFO] [1726762196.863875391] [mavros]: Plugin param initialized 
[mavros_node-2] [INFO] [1726762196.863885850] [mavros]: Plugin play_tune ignored 
[mavros_node-2] [INFO] [1726762196.863891566] [mavros]: Plugin px4flow ignored 
[mavros_node-2] [INFO] [1726762196.863897119] [mavros]: Plugin rallypoint ignored 
[mavros_node-2] [INFO] [1726762196.863903289] [mavros]: Plugin rangefinder ignored 
[mavros_node-2] [INFO] [1726762196.873092620] [mavros]: Plugin rc_io created 
[mavros_node-2] [INFO] [1726762196.873149327] [mavros]: Plugin rc_io initialized 
[mavros_node-2] [INFO] [1726762196.873156220] [mavros]: Plugin setpoint_accel ignored 
[mavros_node-2] [INFO] [1726762196.873160176] [mavros]: Plugin setpoint_attitude ignored 
[mavros_node-2] [INFO] [1726762196.873163921] [mavros]: Plugin setpoint_position ignored 
[mavros_node-2] [INFO] [1726762196.873167822] [mavros]: Plugin setpoint_raw ignored 
[mavros_node-2] [INFO] [1726762196.873171567] [mavros]: Plugin setpoint_trajectory ignored 
[mavros_node-2] [INFO] [1726762196.873175259] [mavros]: Plugin setpoint_velocity ignored 
[mavros_node-2] [INFO] [1726762196.888748252] [mavros]: Plugin sys_status created 
[mavros_node-2] [INFO] [1726762196.888862840] [mavros]: Plugin sys_status initialized 
[mavros_node-2] [INFO] [1726762196.888875598] [mavros]: Plugin sys_time ignored 
[mavros_node-2] [INFO] [1726762196.888881402] [mavros]: Plugin tdr_radio ignored 
[mavros_node-2] [INFO] [1726762196.888885104] [mavros]: Plugin terrain ignored 
[mavros_node-2] [INFO] [1726762196.888888854] [mavros]: Plugin trajectory ignored 
[mavros_node-2] [INFO] [1726762196.888892286] [mavros]: Plugin tunnel ignored 
[mavros_node-2] [INFO] [1726762196.888896733] [mavros]: Plugin vfr_hud ignored 
[mavros_node-2] [INFO] [1726762196.888900278] [mavros]: Plugin vibration ignored 
[ardusub_manager-9] [INFO] [1726762196.891986581] [ardusub_manager]: Configuring the ArduSub manager... 
[ardusub_manager-9] [INFO] [1726762196.895766617] [ardusub_manager]: Successfully configured the ArduSub manager! 
[ardusub_manager-9] [INFO] [1726762196.897886339] [ardusub_manager]: Activating the ArduSub manager... 
[ardusub_manager-9] [INFO] [1726762196.898007332] [ardusub_manager]: Successfully activated the ArduSub manager! 
[mavros_node-2] [INFO] [1726762196.908236982] [mavros]: Plugin vision_pose created 
[mavros_node-2] [INFO] [1726762196.908287367] [mavros]: Plugin vision_pose initialized 
[mavros_node-2] [INFO] [1726762196.919086579] [mavros]: Plugin vision_speed created 
[mavros_node-2] [INFO] [1726762196.919171249] [mavros]: Plugin vision_speed initialized 
[mavros_node-2] [INFO] [1726762196.919187634] [mavros]: Plugin waypoint ignored 
[mavros_node-2] [INFO] [1726762196.919194160] [mavros]: Plugin wheel_odometry ignored 
[mavros_node-2] [INFO] [1726762196.919201237] [mavros]: Plugin wind_estimation ignored 
[mavros_node-2] [INFO] [1726762196.921703745] [mavros]: Built-in SIMD instructions: SSE, SSE2 
[mavros_node-2] [INFO] [1726762196.921763907] [mavros]: Built-in MAVLink package version: 2024.6.6 
[mavros_node-2] [INFO] [1726762196.921774683] [mavros]: Known MAVLink dialects: common ardupilotmega ASLUAV AVSSUAS all csAirLink cubepilot development icarous matrixpilot paparazzi standard storm32 uAvionix ualberta 
[mavros_node-2] [INFO] [1726762196.921783854] [mavros]: MAVROS UAS via /uas1 started. MY ID 255.191, TARGET ID 1.1 
[mavros_node-2] [INFO] [1726762197.882537505] [mavros_router]: link[1002] detected remote address 255.191 
[mavros_node-2] [WARN] [1726762198.891074349] [mavros.sys]: VER: broadcast request timeout, retries left 4 
[mavros_node-2] [WARN] [1726762199.890719034] [mavros.sys]: VER: broadcast request timeout, retries left 3 
[mavros_node-2] [WARN] [1726762200.890055138] [mavros.sys]: VER: unicast request timeout, retries left 2 
[create-6] [INFO] [1726762201.728327419] [ros_gz_sim]: Requesting list of world names. 
[mavros_node-2] [WARN] [1726762201.890855913] [mavros.sys]: VER: unicast request timeout, retries left 1 
[mavros_node-2] [WARN] [1726762202.891402545] [mavros.sys]: VER: unicast request timeout, retries left 0 
[mavros_node-2] [WARN] [1726762203.890122775] [mavros.sys]: VER: your FCU don't support AUTOPILOT_VERSION, switched to default capabilities 
[create-6] [INFO] [1726762206.728549269] [ros_gz_sim]: Requesting list of world names. 
[ruby $(which gz) sim-8] [Wrn] [Gui.cc:271] Waited for 10s for a subscriber to [/gazebo/starting_world] and got none. 
[ruby $(which gz) sim-8] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-blue' 
[create-6] [INFO] [1726762211.728874671] [ros_gz_sim]: Requesting list of world names. 
```

**Comment by evan-palmer** [comment] 2024-09-19 19:19
Closing this now in favor of adding documentation in #310

**Closed by evan-palmer** 2024-09-19 19:19 UTC
Labels: bug

**Comment by Manouselis** [comment] 2025-04-29 12:04
Neither disabling the firewall or enabling multicast solves the issue for me. I still get:
```
mavros_node-2] [INFO] [1745928038.017888232] [mavros]: MAVROS UAS via /uas1 started. MY ID 255.191, TARGET ID 1.1
[ardusub_manager-3] [INFO] [1745928038.108005189] [ardusub_manager]: Configuring the ArduSub manager...
[ardusub_manager-3] [INFO] [1745928038.114755491] [ardusub_manager]: Successfully configured the ArduSub manager!
[ardusub_manager-3] [INFO] [1745928038.116763647] [ardusub_manager]: Activating the ArduSub manager...
[ardusub_manager-3] [INFO] [1745928038.116858375] [ardusub_manager]: Successfully activated the ArduSub manager!
[mavros_node-2] [INFO] [1745928038.989791076] [mavros_router]: link[1002] detected remote address 255.191
[mavros_node-2] [WARN] [1745928039.998640589] [mavros.sys]: VER: broadcast request timeout, retries left 4
[mavros_node-2] [WARN] [1745928040.998200446] [mavros.sys]: VER: broadcast request timeout, retries left 3
[mavros_node-2] [WARN] [1745928041.999149605] [mavros.sys]: VER: unicast request timeout, retries left 2
[mavros_node-2] [WARN] [1745928042.999624141] [mavros.sys]: VER: unicast request timeout, retries left 1
[mavros_node-2] [WARN] [1745928043.997939213] [mavros.sys]: VER: unicast request timeout, retries left 0
[mavros_node-2] [WARN] [1745928044.997959031] [mavros.sys]: VER: your FCU don't support AUTOPILOT_VERSION, switched to default capabilities
[mavros_node-2] [INFO] [1745928067.885094908] [mavros_router]: link[1000] trying to reconnect...
[mavros_node-2] [ERROR] [1745928067.885624405] [mavros_router]: link[1000] reconnect failed: DeviceError:tcp:connect: Connection refused
[mavros_node-2] [INFO] [1745928097.884762693] [mavros_router]: link[1000] trying to reconnect...
[mavros_node-2] [ERROR] [1745928097.885329957] [mavros_router]: link[1000] reconnect failed: DeviceError:tcp:connect: Connection refused
[mavros_node-2] [INFO] [1745928127.884543300] [mavros_router]: link[1000] trying to reconnect...
[mavros_node-2] [ERROR] [1745928127.885127594] [mavros_router]: link[1000] reconnect failed: DeviceError:tcp:connect: Connection refused
```
I am running the `humbe-desktop-nvidia` image

**Comment by evan-palmer** [comment] 2025-04-30 05:24
> Neither disabling the firewall or enabling multicast solves the issue for me. I still get: ...

Hmm that's weird. Would you be willing to open a new issue and attach the full log @Manouselis?

**Comment by Manouselis** [comment] 2025-05-01 07:09
Hi @evan-palmer , there were two issues. One was my own mistake: forgetting to add the `use_sim:=true` argument, the second one was that in some cases when running the simulation my ram was immediatelly completely filled (32GB - 100%) causing everything to crash.  Those issues are now resolved for me

I do have another problem. I'm composing the gpu accelerated image (using `nvidia-desktop.yaml `) . However, this gpu accelerated image (`humble-desktop-nvidia`) is not running on the GPU, using instead the cpu. Even on my Intel i9-13950HX, the simulation is sluggish. I would like to use my dedicated GPU.  Should I open a new issue and attach the full log reagrding that, there?

**Comment by evan-palmer** [comment] 2025-05-01 23:07
> Should I open a new issue and attach the full log reagrding that, there?

Please do @Manouselis!

**Comment by Manouselis** [comment] 2025-05-06 09:21
Hi @evan-palmer, thank you for your quick reply.

1. The NVIDIA container toolkit is correctly installed.
2. Disabling the textures indeed helps.

I will open an issue with the container logs shortly.
